# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-05 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20160905_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizglobal',
            name='duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='quizglobal',
            name='mmcc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='quizglobal',
            name='mmci',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='quizglobal',
            name='mscc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='quizglobal',
            name='msci',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
