# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-05 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_auto_20160905_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizglobal',
            name='marking',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='quizglobal',
            name='prizes',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
