# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-05 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_delete_quizglobal'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizGlobal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=1000)),
                ('quizname', models.CharField(max_length=5000)),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('marking', models.CharField(blank=True, max_length=10000, null=True)),
                ('prizes', models.CharField(blank=True, max_length=10000, null=True)),
                ('mscc', models.IntegerField(blank=True, null=True)),
                ('msci', models.IntegerField(blank=True, null=True)),
                ('mmcc', models.IntegerField(blank=True, null=True)),
                ('mmci', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
