# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-10 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_quizglobal'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizglobal',
            name='minputypecorrect',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizglobal',
            name='minputypeincorrect',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
