# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-12 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_auto_20160913_0211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
